### ISSUE TITLE
main.ERROR stacktrace from panic: runtime error: slice bounds out of range [:2] with capacity 0

### ISSUE THREAD

**Issue by izedgo** [yandex-cloud/geesefs#5]
main.ERROR stacktrace from panic: runtime error: slice bounds out of range [:2] with capacity 0 #012goroutine 277553 [running]:#012runtime/debug.Stack(0xc000615970, 0x10af760, 0xc017d0a000)#012#011/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/debug/stack.go:24 +0x9f#012github.com/yandex-cloud/geesefs/api/common.LogPanic(0xc000615f38)#012#011/home/runner/work/geesefs/geesefs/api/common/panic_logger.go:32 +0x76#012panic(0x10af760, 0xc017d0a000)#012#011/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:965 +0x1b9#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0018fa600)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:840 +0x165#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0018fa300)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0018f9e00)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000b62d80)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0013ec180)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000ea9500)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc00070d680)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3#012github.com/yandex-cloud/geesefs/internal.(*DirHandle).ReadDir(0xc012fd4020, 0x0, 0x0, 0xc001356060, 0x1, 0x1)#012#011/home/runner/work/geesefs/geesefs/internal/dir.go:572 +0x210#012github.com/yandex-cloud/geesefs/internal.(*Goofys).ReadDir(0xc000416000, 0x133b0b8, 0xc013d9a150, 0xc003696840, 0x0, 0xc016902d20)#012#011/home/runner/work/geesefs/geesefs/internal/goofys.go:1127 +0x265#012github.com/yandex-cloud/geesefs/api/common.FusePanicLogger.ReadDir(0x134b380, 0xc000416000, 0x133b0b8, 0xc013d9a150, 0xc003696840, 0x0, 0x0)#012#011/home/runner/work/geesefs/geesefs/api/common/panic_logger.go:101 +0x8c#012github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc0003bf3c0, 0xc00048e9c0, 0x133b0b8, 0xc013d9a150, 0xf4b320, 0xc003696840)#012#011/home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20210901111451-575b70f3fd32/fuseutil/file_system.go:183 +0xc87#012created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps#012#011/home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20210901111451-575b70f3fd32/fuseutil/file_system.go:123 +0x1a5

fuse.ERROR *fuseops.ReadDirOp error: input/output error

**Comment by vitalif** [comment]
Hi. Cool. Can you provide any additional information on what you tried to do with the file system when it crashed? :-)

**Comment by izedgo** [comment]
Привет! Папка была примонтирована к веб-серверу, а через какое то время отвалилась, повторно уже не монтировалась, пришлось перезагрузить ВМ.

**Comment by vitalif** [comment]
Повторно после паники можно монтировать, если сделать просто sudo umount точки монтирования. Просто после падения процесса-обработчика ФС точка монтирования остаётся в некорректном состоянии.
А что делал вебсервер - просто раздавал статику? Запись шла туда?

**Comment by alex-v-jc** [comment]
Окружение.

```4.18.0-240.10.1.el8_3.x86_64
CentOS Linux release 8.3.2011

geesefs version 0.28.4

fuse-overlayfs-1.6-1.module_el8.4.0+886+c9a8d9ad.x86_64
fuse3-libs-3.2.1-12.el8.x86_64
fuse3-3.2.1-12.el8.x86_64
s3fs-fuse-1.90-1.el8.x86_64
fuse-common-3.2.1-12.el8.x86_64
fuse-2.9.7-12.el8.x86_64
fuse-libs-2.9.7-12.el8.x86_64
```

В произвольный момент возникает ситуация, указанная ниже.
Можно воспроизвести со 100%-ной вероятностью просто при серфинге каталогов.
Причем, зависимости от большого числа файлов не замечено.

Какие еще данные нужны для анализа?

```
2021/10/04 22:52:39.303735 main.ERROR stacktrace from panic: runtime error: slice bounds out of range [:2] with capacity 0
goroutine 86 [running]:
runtime/debug.Stack(0xc000da3930, 0x10af760, 0xc000376990)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/debug/stack.go:24 +0x9f
github.com/yandex-cloud/geesefs/api/common.LogPanic(0xc000da3f38)
        /home/runner/work/geesefs/geesefs/api/common/panic_logger.go:32 +0x76
panic(0x10af760, 0xc000376990)
        /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:965 +0x1b9
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000b70d80)
        /home/runner/work/geesefs/geesefs/internal/dir.go:840 +0x165
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000b70c00)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000b70780)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000b70300)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000473e00)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc000473980)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0002e9c80)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*Inode).removeAllChildrenUnlocked(0xc0002e8c00)
        /home/runner/work/geesefs/geesefs/internal/dir.go:828 +0xd3
github.com/yandex-cloud/geesefs/internal.(*DirHandle).ReadDir(0xc000d92780, 0x0, 0x0, 0xc000da8530, 0x1, 0x1)
        /home/runner/work/geesefs/geesefs/internal/dir.go:572 +0x210
github.com/yandex-cloud/geesefs/internal.(*Goofys).ReadDir(0xc0000b0000, 0x133b0b8, 0xc000c90720, 0xc000a3ec00, 0x0, 0x0)
        /home/runner/work/geesefs/geesefs/internal/goofys.go:1127 +0x265
github.com/yandex-cloud/geesefs/api/common.FusePanicLogger.ReadDir(0x134b380, 0xc0000b0000, 0x133b0b8, 0xc000c90720, 0xc000a3ec00, 0x0, 0x0)
        /home/runner/work/geesefs/geesefs/api/common/panic_logger.go:101 +0x8c
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000684460, 0xc000118680, 0x133b0b8, 0xc000c90720, 0xf4b320, 0xc000a3ec00)
        /home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20210901111451-575b70f3fd32/fuseutil/file_system.go:183 +0xc87
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20210901111451-575b70f3fd32/fuseutil/file_system.go:123 +0x1a5

2021/10/04 22:52:39.303756 fuse.DEBUG Op 0x00000040        connection.go:502] -> Error: "input/output error"
2021/10/04 22:52:39.303767 fuse.ERROR *fuseops.ReadDirOp error: input/output error
```

**Comment by alex-v-jc** [comment]
> Повторно после паники можно монтировать, если сделать просто sudo umount точки монтирования. Просто после падения процесса-обработчика ФС точка монтирования остаётся в некорректном состоянии. А что делал вебсервер - просто раздавал статику? Запись шла туда?

примонтировать можно, но это не на долго
это происходит постоянно

**Comment by vitalif** [comment]
Привет, пока 2 вещи могу предложить:
1) попробуйте воспроизвести на той версии, что я вот только что запушил в мастер. там чисто теоретическое исправление, но вдруг поможет :-)
2) попробуйте собрать отладочный лог путём запуска `geesefs --debug_fuse --debug_s3 --log-file /path/to/debug.log`. там будет access key id, так что перед выкладыванием, возможно, его придётся выпилить из лога. запустите, воспроизведите баг, выложите лог

**Comment by vitalif** [comment]
Чисто умозрительно вот эта конкретная ситуация с паникой была возможна, если только в S3 был одновременно и файл, и директория с одним и тем же именем - ну т.е., например, объекты a/b и a/b/c. В S3 это ведь возможно, а в ФС нет. В этой ситуации могло выйти так, что geesefs "превращал" в кэше файл в директорию, и это могло приводить к гонке из-за того, что файл был уже превращён в директорию, а записи "." и ".." в неё добавлены ещё не были. Причём, на самом деле, само добавление этих записей "." и ".." - это наследие goofys, в моём понимании это совершенно не нужно, я бы их просто добавлял в вывод в начале readdir и не хранил как реальные объекты во внутреннем дереве ФС... ну, может быть, так и сделаю позже. А пока что сделал, чтобы файл в этой ситуации не превращался в директорию, а заменялся директорией.

В общем, выложил 0.28.5, попробуйте её.

**Comment by alex-v-jc** [comment]
Воспроизводится.

Есть лог такого сценария:

- подключаемся
- ходим по каталогам, смотрим содержимое,....
- копируем ~1К мелких файлов
- копирование выполняется
- падение

Уверен, что, если бы я дольше "ползал" по каталогом, оно бы тоже упало.

Куда выслать лог?

**Comment by vitalif** [comment]
Кинь на vitalif@mail.ru например

**Comment by vitalif** [comment]
ЗЫ Сейчас ещё один фикс внёс, можешь ещё попробовать 0.28.6

**Comment by alex-v-jc** [comment]
Ну, ситуация стало несколько лучше, но не идеальной.
Паники в логе нет, но, опять таки, в произвольный момент папка просто перестает "отзываться".
Система "зависает" на попытке получить какой-то респонс.
Если повезет, через какое-то время может отмереть по таймауту, вот в mc один раз я дождался, пока mc "сказал", все, не могу...
А вот cp завесил напрочь.
Все запуски были с логами, но... чего-то очевидного, как панику, я в них не нашел.
Если больше никаких патчей не ожидается, могу выслать логи...

**Comment by vitalif** [comment]
Если наблюдается именно дедлок, т.е. если операции подвисают и geesefs ничего не делает (логи не идут, в top нагрузки cpu нет), можно через https://github.com/go-delve/delve стеки горутин снять, типа `sudo dlv attach 17410 --allow-non-terminal-interactive=true > grs.txt`, и ввести `grs -t <enter> <ctrl-D> n <enter>`. Полученный файлик кинуть мне, будет информативно, я так ловлю...

Логи тоже кидай, я пока вообще не очень понимаю, что там может такого происходить, что всё валится, есть какие-то нюансы. По крайней мере я сейчас вполне успешно ~30000 файлов из тестового бакета туда-сюда копирую и ничего не подвисает и не паникует...

**Comment by vitalif** [comment]
Просто даже вот та паника с [:2] это какая-то фигня, я не очень понимаю, как это возможно. В коде везде где создаётся директория, в неё сразу добавляются 2 элемента "." и "..". То что оно падало - это значит оно где-то находило объект директории, в котором нет этих "." и "..". Но каким образом оно его находило, раз они всегда сразу добавляются - фиг знает, тем более при таких простых вещах как просто сёрфинг по каталогам или cp. В общем есть какие-то нюансы, которые я пока не улавливаю - ну надо логи посмотреть, может уловлю.
