### ISSUE TITLE
geesefs 0.38.3 crash

### ISSUE THREAD

**Issue by enp** [yandex-cloud/geesefs#98]
Install with `helm install --namespace s3 --set secret.accessKey=<...> --set secret.secretKey=<..> csi-s3 yandex-s3/csi-s3`  in yandex managed kubernetes + yandex object storage with default options

Works in simple cases but crashes on parallel write processes sometimes (can't reproduce every time) with error:

```
2023/12/22 10:23:10.105051 s3.WARNING Conflict detected (inode 437): failed to copy xyz/release to xyz/release.old: NotFound: Not Found
        status code: 404, request id: cd903bcf4d54ff5c, host id: . File is removed remotely, dropping cache
panic: xyz.removeName(release.old) but child not found: 5
goroutine 79859 [running]:
github.com/yandex-cloud/geesefs/internal.(*Inode).removeChildUnlocked(0xc000928000, 0xc0030e9000)
        /home/runner/work/geesefs/geesefs/internal/dir.go:983 +0x45f
github.com/yandex-cloud/geesefs/internal.(*Inode).SendUpload.func1()
        /home/runner/work/geesefs/geesefs/internal/file.go:1364 +0x4ef
created by github.com/yandex-cloud/geesefs/internal.(*Inode).SendUpload
        /home/runner/work/geesefs/geesefs/internal/file.go:1330 +0x38d
geesefs-enp_2dstorage.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Found error string in code - https://github.com/yandex-cloud/geesefs/blob/v0.38.3/internal/dir.go#L983 - so what this case means why geesefs should crash?

More general question: how other cases with `panic` as result should be processed by end user if occurred?

**Comment by vitalif** [comment]
This seems like a nontrivial rename conflict, i.e. you rename the same file to the same destination in parallel multiple times from independent mountpoints, or maybe even multiple times in one mountpoint.

I tried to reproduce it with `for i in {1..100}; do mv renames/$i renames2/$i; done` in two mountpoints in parallel but it didn't reproduce. So I added a symptomatic fix in master branch to prevent panic, but it would be better if you could create a reproduction script for this bug...

>More general question: how other cases with panic as result should be processed by end user if occurred?

Unmount and remount the FS manually, I think... There's no good way to restore dead FUSE mounts in CSI driver (I tried some options), they are left in broken "transport endpoint not connected" state by the kernel and Kubernetes can't repair them - it should at least unmount them first, but it fails to even check the mountpoint when it's broken.

**Comment by Felixoid** [comment]
In https://github.com/ClickHouse/ClickHouse/issues/65229 we faced an issue that the repository became inconsistent

```

root ⟩ deb ⟩ dists ⟩ stable
 
main/
 
InRelease.new    2,490  (2.43kb)                  2024-06-13T11:52:06.060Z
InRelease        2,490  (2.43kb)                  2024-06-07T10:57:45.719Z
Release.gpg.new  833                              2024-06-13T11:52:04.691Z
Release.gpg      833                              2024-06-07T10:57:45.783Z
Release.new      1,608  (1.57kb)                  2024-06-13T11:52:00.500Z
Release          1,608  (1.57kb)                  2024-06-07T10:57:44.940Z
```

in the syslog there's a line at the moment when it happened

```
Jun 13 11:52:06 ip-172-31-87-196 /usr/bin/geesefs[134610]: s3.WARNING Conflict detected (inode 10911): server-side ETag or size of deb/dists/stable/InRelease ("a656d995d5b24e00d0faf685e99155fc", 2490) differs from local ("335d0ae0ca4ab9e064142f538f765922", 2490). File is changed remotely, dropping cache
Jun 13 11:52:06 ip-172-31-87-196 /usr/bin/geesefs[134610]: s3.WARNING Conflict detected (inode 10910): server-side ETag or size of deb/dists/stable/Release.gpg ("a5b36fabe012f701148a689e509713fd", 833) differs from local ("ccf34d825275968affe8fe7e73c6d463", 833). File is changed remotely, dropping cache
Jun 13 11:52:06 ip-172-31-87-196 /usr/bin/geesefs[134610]: s3.WARNING Conflict detected (inode 10909): server-side ETag or size of deb/dists/stable/Release ("4af3bcc265ecb74abfeac9aec278e9e0", 1608) differs from local ("61cc200dfc964c2eb4b81c734eb363fc", 1608). File is changed remotely, dropping cache

Jun 13 16:04:10 ip-172-31-87-196 /usr/bin/geesefs[134610]: s3.WARNING Conflict detected (inode 10994): server-side ETag or size of deb/dists/lts/Release.gpg ("e94a77fd9ce0fa1a4083c465bc113a36", 833) differs from local ("74ac4f05da5f332153eecc8d768a06c6", 833). File is changed remotely, dropping cache
```

It's very dangerous for us =\

**Comment by Felixoid** [comment]
Another appearance from today

`Jun 14 17:12:21 ip-172-31-87-196 /usr/bin/geesefs[164712]: s3.WARNING Conflict detected (inode 5331): server-side ETag or size of deb/dists/stable/InRelease ("b9d2f4d2c707c2236e8f02d787204d88", 2490) differs from local ("ccd5ccc1d800e42f7bafb8cb1532c18c", 2490). File is changed remotely, dropping cache`

**Comment by Felixoid** [comment]
Dear colleagues, it breaks our pipeline completely because the Debian repos are inconsistent. Some files remain from the previous deployment, and some are new

```
Jul  1 08:37:35 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO File system has been successfully mounted.
Jul  1 08:37:36 ip-172-31-87-196 /usr/bin/geesefs[164712]: main.INFO Successfully exiting.
Jul  1 08:38:05 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 0.00 write/s; metadata: 0.26 read/s, 0.00 write/s, 0.00 noop/s, 3001 alive, 0.00 evict/s; 0.00 flush/s
Jul  1 08:38:35 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 0.00 write/s; metadata: 0.00 read/s, 0.00 write/s, 0.00 noop/s, 3001 alive, 0.00 evict/s; 0.00 flush/s
Jul  1 08:43:05 ip-172-31-87-196 /usr/bin/geesefs[228098]: message repeated 9 times: [ main.INFO I/O: 0.00 read/s, 0.00 % hits, 0.00 write/s; metadata: 0.00 read/s, 0.00 write/s, 0.00 noop/s, 3001 alive, 0.00 evict/s; 0.00 flush/s]
Jul  1 08:43:35 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 0.00 write/s; metadata: 0.07 read/s, 0.00 write/s, 0.00 noop/s, 3001 alive, 0.00 evict/s; 0.00 flush/s
Jul  1 08:44:05 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 2.30 read/s, 0.00 % hits, 1087.46 write/s; metadata: 1089.50 read/s, 0.10 write/s, 1.13 noop/s, 4381 alive, 0.00 evict/s; 2.67 flush/s
Jul  1 08:44:35 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 1133.73 write/s; metadata: 1134.93 read/s, 0.20 write/s, 0.40 noop/s, 5341 alive, 0.00 evict/s; 4.53 flush/s
Jul  1 08:45:05 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 1251.03 write/s; metadata: 1251.86 read/s, 0.13 write/s, 0.27 noop/s, 5345 alive, 0.00 evict/s; 3.97 flush/s
Jul  1 08:45:35 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 1425.12 write/s; metadata: 1425.52 read/s, 0.03 write/s, 0.13 noop/s, 5346 alive, 0.00 evict/s; 4.07 flush/s
Jul  1 08:46:05 ip-172-31-87-196 /usr/bin/geesefs[228098]: main.INFO I/O: 0.00 read/s, 0.00 % hits, 1385.84 write/s; metadata: 1386.04 read/s, 0.07 write/s, 0.07 noop/s, 5348 alive, 0.00 evict/s; 4.47 flush/s
Jul  1 08:46:24 ip-172-31-87-196 /usr/bin/geesefs[228098]: s3.WARNING Conflict detected (inode 5355): server-side ETag or size of deb/dists/stable/InRelease ("0b45d04f152c92e80be6062ee5629c3c", 2490) differs from local ("0286e7f9fe38846bb3de7754a6bcc396", 2490). File is changed remotely, dropping cache
Jul  1 08:46:24 ip-172-31-87-196 /usr/bin/geesefs[228098]: s3.WARNING Conflict detected (inode 5354): server-side ETag or size of deb/dists/stable/Release.gpg ("3b8175393f32c7f737006a9412123b7b", 833) differs from local ("78a535cc0930faf388a94ed1475a8cfc", 833). File is changed remotely, dropping cache
```

Is there a CLI argument, maybe, to forcibly override the remote files? In our case, we have the only one writer, so it would help.

**Comment by vitalif** [comment]
Which tool do you use to make the repo?

I could try to reproduce it. Or could you at least mount it with --log-file log.txt --debug_s3 --debug_fuse, reproduce the problem once and send us the debug log?

**Comment by Felixoid** [comment]
Hi @vitalif. Sorry for the long silence; I'm on parental leave.

It's reprepro 5.4.1. I am currently trying to build a repo for an isolated laboratory, hopefully will be back with result soon

**Comment by Felixoid** [comment]
Hello. Sorry for such a disappearance.

But I've finally reproduced the issue https://github.com/Felixoid/geesefs-reprepro

I have s3-debug logs with three following lines, but not sure how safe it is to share it as is

```
2024/08/27 17:49:43.000464 s3.WARNING Conflict detected (inode 106): server-side ETag or size of reproduce/deb/dists/lts/main/binary-amd64/Packages.gz ("7029066c27ac6f5ef18d660d5741979a", 20) differs from local ("ec9569352bdc2f5e0bab2d1b3699446b", 1695). File is changed remotely, dropping cache
2024/08/27 17:52:26.580871 s3.WARNING Conflict detected (inode 184): server-side ETag or size of reproduce/deb/dists/lts/Release.gpg ("2efbef751bd8c0af8868ff312011d76d", 659) differs from local ("77ff6a38f3e6f8753a10d5e77e1d4d04", 659). File is changed remotely, dropping cache
2024/08/27 17:57:36.690662 s3.WARNING Conflict detected (inode 322): server-side ETag or size of reproduce/deb/dists/lts/InRelease ("7eec685479e1ffba9f0f1aa16daf3566", 2259) differs from local ("c8379e7a354a3adab3b21dc3cd4bfe70", 2295). File is changed remotely, dropping cache
```

What should I clean from it? there's a lot of Auth stuff and so on

**Comment by Felixoid** [comment]
It feels to me, like the FS reports success before the big files are uploaded. Could `--fsync-on-close` save us in this case?

**Comment by Felixoid** [comment]
Added `--fsync-on-close` didn't help with conflicting ETag

```
2024/08/28 11:04:59.724218 s3.WARNING Conflict detected (inode 296): server-side ETag or size of reproduce/deb/dists/stable/Release ("6089c83c9868d9ae622987eac4d365a2", 1584) differs from local ("e960a07962379de04df349011a1a6070", 1584). File is changed remotely, dropping cache
```

**Comment by Felixoid** [comment]
It is worth saying the next. To reproduce the issue, I've launched the [run.sh](https://github.com/Felixoid/geesefs-reprepro/blob/master/run.sh) many times. So, it's very inconsistent.

I am waiting for the feedback regarding the S3 debug log.

**Comment by Felixoid** [comment]
Thanks a lot, it's fixed by a given commit. To see if the issue is addressed, I've built a special binary:

```diff
diff --git a/internal/handles.go b/internal/handles.go
index 62748a3..72867b3 100644
--- a/internal/handles.go
+++ b/internal/handles.go
@@ -206,6 +206,11 @@ func (inode *Inode) SetFromBlobItem(item *BlobItemOutput) {
        // If a file is renamed from a different file then we also don't know its server-side
        // ETag or Size for sure, so the simplest fix is to also ignore this check
        renameInProgress := inode.oldName != ""
+       if renameInProgress {
+               s3Log.Warnf("Conflict almost detected (inode %v): Server-Side ETag or size of %v"+
+                       " (%v, %v) differs from local (%v, %v). File is changed remotely, dropping cache",
+                       inode.Id, inode.FullName(), NilStr(item.ETag), item.Size, inode.knownETag, inode.knownSize)
+       }

        if (item.ETag != nil && inode.knownETag != *item.ETag || item.Size != inode.knownSize) &&
                !patchInProgress && !renameInProgress {
```

And after that, the following is happened:

```
ubuntu@ip-172-31-91-79:~$ grep 'server-side' ~/geesefs-reprepro/data/geesefs.log;
ubuntu@ip-172-31-91-79:~$ grep 'Conflict almost detected' ~/geesefs-reprepro/data/geesefs.log;
2024/09/03 09:57:37.763639 s3.WARNING Conflict almost detected (inode 351): Server-Side ETag or size of reproduce/configs/deb/db/version ("7c5bcba397349825009d4efef63ea886", 31) differs from local (, 0). File is changed remotely, dropping cache
2024/09/03 10:01:19.684472 s3.WARNING Conflict almost detected (inode 452): Server-Side ETag or size of reproduce/deb/dists/lts/main/binary-amd64/Packages.gz ("ec9569352bdc2f5e0bab2d1b3699446b", 1695) differs from local ("a720ad8bec6a3b1b3776fdd7bcd392fe", 2619). File is changed remotely, dropping cache
```

So the https://packages.clickhouse.com/deb appreciates it very much!
